// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.1
// source: online.proto

package protof

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OnlineWrapperDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Onlines []*OnlineWrapperDto_OnlineDto `protobuf:"bytes,1,rep,name=onlines,proto3" json:"onlines,omitempty"`
}

func (x *OnlineWrapperDto) Reset() {
	*x = OnlineWrapperDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineWrapperDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineWrapperDto) ProtoMessage() {}

func (x *OnlineWrapperDto) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineWrapperDto.ProtoReflect.Descriptor instead.
func (*OnlineWrapperDto) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{0}
}

func (x *OnlineWrapperDto) GetOnlines() []*OnlineWrapperDto_OnlineDto {
	if x != nil {
		return x.Onlines
	}
	return nil
}

type OnlineWrapperDto_OnlineDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	L3Vni        string `protobuf:"bytes,1,opt,name=l3vni,proto3" json:"l3vni,omitempty"`
	L2Vni        string `protobuf:"bytes,2,opt,name=l2vni,proto3" json:"l2vni,omitempty"`
	SubnetGwMac  string `protobuf:"bytes,3,opt,name=subnetGwMac,proto3" json:"subnetGwMac,omitempty"`
	SubnetGwIp   string `protobuf:"bytes,4,opt,name=subnetGwIp,proto3" json:"subnetGwIp,omitempty"`
	SubnetMask   string `protobuf:"bytes,5,opt,name=subnetMask,proto3" json:"subnetMask,omitempty"`
	SubnetGwIpv6 string `protobuf:"bytes,6,opt,name=subnetGwIpv6,proto3" json:"subnetGwIpv6,omitempty"`
	SubnetMaskV6 string `protobuf:"bytes,7,opt,name=subnetMaskV6,proto3" json:"subnetMaskV6,omitempty"`
	NicIndex     string `protobuf:"bytes,8,opt,name=nicIndex,proto3" json:"nicIndex,omitempty"`
	NicName      string `protobuf:"bytes,9,opt,name=nicName,proto3" json:"nicName,omitempty"`
	NicMac       string `protobuf:"bytes,10,opt,name=nicMac,proto3" json:"nicMac,omitempty"`
	NicIp        string `protobuf:"bytes,11,opt,name=nicIp,proto3" json:"nicIp,omitempty"`
	NicIpv6Ip    string `protobuf:"bytes,12,opt,name=nicIpv6Ip,proto3" json:"nicIpv6Ip,omitempty"`
	NicCvkIp     string `protobuf:"bytes,13,opt,name=nicCvkIp,proto3" json:"nicCvkIp,omitempty"`
	BgpAsNumber  string `protobuf:"bytes,14,opt,name=bgpAsNumber,proto3" json:"bgpAsNumber,omitempty"`
	Rt           string `protobuf:"bytes,15,opt,name=rt,proto3" json:"rt,omitempty"`
	OnlineType   string `protobuf:"bytes,16,opt,name=onlineType,proto3" json:"onlineType,omitempty"`
}

func (x *OnlineWrapperDto_OnlineDto) Reset() {
	*x = OnlineWrapperDto_OnlineDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineWrapperDto_OnlineDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineWrapperDto_OnlineDto) ProtoMessage() {}

func (x *OnlineWrapperDto_OnlineDto) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineWrapperDto_OnlineDto.ProtoReflect.Descriptor instead.
func (*OnlineWrapperDto_OnlineDto) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{0, 0}
}

func (x *OnlineWrapperDto_OnlineDto) GetL3Vni() string {
	if x != nil {
		return x.L3Vni
	}
	return ""
}

func (x *OnlineWrapperDto_OnlineDto) GetL2Vni() string {
	if x != nil {
		return x.L2Vni
	}
	return ""
}

func (x *OnlineWrapperDto_OnlineDto) GetSubnetGwMac() string {
	if x != nil {
		return x.SubnetGwMac
	}
	return ""
}

func (x *OnlineWrapperDto_OnlineDto) GetSubnetGwIp() string {
	if x != nil {
		return x.SubnetGwIp
	}
	return ""
}

func (x *OnlineWrapperDto_OnlineDto) GetSubnetMask() string {
	if x != nil {
		return x.SubnetMask
	}
	return ""
}

func (x *OnlineWrapperDto_OnlineDto) GetSubnetGwIpv6() string {
	if x != nil {
		return x.SubnetGwIpv6
	}
	return ""
}

func (x *OnlineWrapperDto_OnlineDto) GetSubnetMaskV6() string {
	if x != nil {
		return x.SubnetMaskV6
	}
	return ""
}

func (x *OnlineWrapperDto_OnlineDto) GetNicIndex() string {
	if x != nil {
		return x.NicIndex
	}
	return ""
}

func (x *OnlineWrapperDto_OnlineDto) GetNicName() string {
	if x != nil {
		return x.NicName
	}
	return ""
}

func (x *OnlineWrapperDto_OnlineDto) GetNicMac() string {
	if x != nil {
		return x.NicMac
	}
	return ""
}

func (x *OnlineWrapperDto_OnlineDto) GetNicIp() string {
	if x != nil {
		return x.NicIp
	}
	return ""
}

func (x *OnlineWrapperDto_OnlineDto) GetNicIpv6Ip() string {
	if x != nil {
		return x.NicIpv6Ip
	}
	return ""
}

func (x *OnlineWrapperDto_OnlineDto) GetNicCvkIp() string {
	if x != nil {
		return x.NicCvkIp
	}
	return ""
}

func (x *OnlineWrapperDto_OnlineDto) GetBgpAsNumber() string {
	if x != nil {
		return x.BgpAsNumber
	}
	return ""
}

func (x *OnlineWrapperDto_OnlineDto) GetRt() string {
	if x != nil {
		return x.Rt
	}
	return ""
}

func (x *OnlineWrapperDto_OnlineDto) GetOnlineType() string {
	if x != nil {
		return x.OnlineType
	}
	return ""
}

var File_online_proto protoreflect.FileDescriptor

var file_online_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9d,
	0x04, 0x0a, 0x10, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72,
	0x44, 0x74, 0x6f, 0x12, 0x35, 0x0a, 0x07, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x57, 0x72, 0x61,
	0x70, 0x70, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x2e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x44, 0x74,
	0x6f, 0x52, 0x07, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x1a, 0xd1, 0x03, 0x0a, 0x09, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x44, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x33, 0x76, 0x6e,
	0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x33, 0x76, 0x6e, 0x69, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x32, 0x76, 0x6e, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c,
	0x32, 0x76, 0x6e, 0x69, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x47, 0x77,
	0x4d, 0x61, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x75, 0x62, 0x6e, 0x65,
	0x74, 0x47, 0x77, 0x4d, 0x61, 0x63, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74,
	0x47, 0x77, 0x49, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x6e,
	0x65, 0x74, 0x47, 0x77, 0x49, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74,
	0x4d, 0x61, 0x73, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x6e,
	0x65, 0x74, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74,
	0x47, 0x77, 0x49, 0x70, 0x76, 0x36, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x75,
	0x62, 0x6e, 0x65, 0x74, 0x47, 0x77, 0x49, 0x70, 0x76, 0x36, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x75,
	0x62, 0x6e, 0x65, 0x74, 0x4d, 0x61, 0x73, 0x6b, 0x56, 0x36, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x4d, 0x61, 0x73, 0x6b, 0x56, 0x36, 0x12, 0x1a,
	0x0a, 0x08, 0x6e, 0x69, 0x63, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6e, 0x69, 0x63, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x69,
	0x63, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x69, 0x63,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x69, 0x63, 0x4d, 0x61, 0x63, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x69, 0x63, 0x4d, 0x61, 0x63, 0x12, 0x14, 0x0a, 0x05,
	0x6e, 0x69, 0x63, 0x49, 0x70, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x69, 0x63,
	0x49, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x69, 0x63, 0x49, 0x70, 0x76, 0x36, 0x49, 0x70, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x69, 0x63, 0x49, 0x70, 0x76, 0x36, 0x49, 0x70,
	0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x43, 0x76, 0x6b, 0x49, 0x70, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x43, 0x76, 0x6b, 0x49, 0x70, 0x12, 0x20, 0x0a, 0x0b,
	0x62, 0x67, 0x70, 0x41, 0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x62, 0x67, 0x70, 0x41, 0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x0e,
	0x0a, 0x02, 0x72, 0x74, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x72, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x10, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x42, 0x1a,
	0x5a, 0x18, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2d, 0x63, 0x76, 0x6b, 0x2d, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_online_proto_rawDescOnce sync.Once
	file_online_proto_rawDescData = file_online_proto_rawDesc
)

func file_online_proto_rawDescGZIP() []byte {
	file_online_proto_rawDescOnce.Do(func() {
		file_online_proto_rawDescData = protoimpl.X.CompressGZIP(file_online_proto_rawDescData)
	})
	return file_online_proto_rawDescData
}

var file_online_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_online_proto_goTypes = []interface{}{
	(*OnlineWrapperDto)(nil),           // 0: OnlineWrapperDto
	(*OnlineWrapperDto_OnlineDto)(nil), // 1: OnlineWrapperDto.OnlineDto
}
var file_online_proto_depIdxs = []int32{
	1, // 0: OnlineWrapperDto.onlines:type_name -> OnlineWrapperDto.OnlineDto
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_online_proto_init() }
func file_online_proto_init() {
	if File_online_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_online_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineWrapperDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineWrapperDto_OnlineDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_online_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_online_proto_goTypes,
		DependencyIndexes: file_online_proto_depIdxs,
		MessageInfos:      file_online_proto_msgTypes,
	}.Build()
	File_online_proto = out.File
	file_online_proto_rawDesc = nil
	file_online_proto_goTypes = nil
	file_online_proto_depIdxs = nil
}
